config/routes.rb
Rails.application.routes.draw do
  root 'establishments#index'

  ActiveAdmin.routes(self)
  devise_for :users
  resources :establishments do
    resources :reviews, :only => [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :establishments, dependent: :destroy	
end

app/models/establishment.rb
class Establishment < ApplicationRecord

	has_many :images, dependent: :destroy	
	has_many :reviews, dependent: :destroy	
	belongs_to :category	
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :user
	belongs_to :establishment

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :establishment	
	belongs_to :user

	def average_feed_rate
    average = self.reviews.average(:feed_rate)
    return average_round(average)
	end

	def average_service_rate
		average = self.reviews.average(:service_rate)
    return average_round(average)
	end

	def average_atmosphere_rate
		average = self.reviews.average(:atmosphere_rate)
    return average_round(average)
	end

	def average_rate
		average = self.reviews.average(:atmosphere_rate, :feed_rate, :service_rate)
    return average_round(average)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :surname, presence: true, length: {minimum: 2, maximum: 20}
	
	has_many :images, dependent: :destroy	
	has_many :establishments, dependent: :destroy	
  has_many :reviews, dependent: :destroy  
  
	def status?(s)
	  status.include? s.to_s
	end
	
	def full_name
    [
      name,
      surname
    ].reject(&:blank?).join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

	private

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
	  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname])
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    Category.destroy(params[:id])

    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  def new
    @establishment = Establishment.new
  end

  def create
    @establishment = Establishment.new(establishment_params)

    if @establishment.save
      redirect_to @establishment
    else
      render 'new'
    end
  end

  def edit
    @establishment = Establishment.find(params[:id])
  end

  def update
    @establishment = Establishment.find(params[:id])

    if @establishment.update(establishment_params)
      redirect_to @establishment
    else
      render 'edit'
    end
  end

  def destroy
    @establishment = Establishment.destroy(params[:id])
    redirect_to establishments_url
  end

  def index
    @establishments = Establishment.all
  end

  def show
    @establishment = Establishment.find(params[:id])
  end

  private

  def establishment_params
    params.require(:establishment).permit(:title, :description, :status, :image_id, :user_id, :category_id)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	before_action :authenticate_user!, only: [:destroy]
	before_action :set_image, only: [:show, :destroy, :owned_post]
	before_action :owned_photo, only: [:destroy]
	
	def index
	  @images = Image.all.order('created_at DESC')
	end

	def new
	  @image = current_user.images.build
	end
	
	def create
	  @image = current_user.images.build(images_params)
	  if @image.save
	    flash[:success] = "Your post has been created!"
	    redirect_to images_path
	  else
	    flash[:alert] = "Your new post couldn't be created!  Please check the form."
	    render :new
	  end
	end
	
	def show
	end
	
	def destroy
	  @image.destroy
	  redirect_to images_path
	end

	private

	def images_params
	  params.require(:image).permit(:image)
	end

	def set_image
	  @image = Image.find(params[:id])
	end

	def owned_image
		unless current_user == @image.user
	  flash[:alert] = "That post doesn't belong to you!"
	  redirect_to root_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    Review.destroy(params[:id])

    redirect_to root_path
  end

  def review_params
    params.require(:review).permit(:review_comment, :feed_rate, :service_rate, :atmosphere_rate, :user_id, :establishment_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/establishment_helper.rb
module EstablishmentHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/establishments/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Establishments <%= link_to 'New Place', new_establishment_path, class: 'btn btn-default' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>

  <% @establishments.each do |establishment| %>
      <tr>
        <td><%= image_tag(establishment.image_url(:thumb)) if establishment.image? %></td>
        <td><%= link_to establishment.title, establishment_path(establishment) %></td>
        <td><%= establishment.description %></td>
        <td><%= establishment.category.title %></td>
        <td>
          <%= link_to 'View', establishment_path(establishment) %>
          <%= link_to 'Edit', edit_establishment_path(establishment) %>
          <%= link_to 'Delete', establishment_path(establishment),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this establishment?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/establishments/new.html.erb
<%= form_for @establishment, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @establishment.errors[:title].any? %>">
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @establishment.errors[:description].any? %>">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @establishment.errors[:category_id].any? %>">
      <%= f.label :category_id, 'Category', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select :category_id, Category.all, :id, :title, {}, class: 'form-control' %>
      </div>
    </div>

    <%= f.file_field :images, multiple: true %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/establishments/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= @establishment.title %></h1>
    <p><%= @establishment.description %></p>
    <%= image_tag(@establishment.image_url(:full)) if @establishment.image? %>
    
    <div class="col-md-6 ">
      <% if user_signed_in? %>
        <div >
          <h3>Add review</h3>
          <%= form_for [@establishment, @establishment.reviews.build] do |f| %>
              <div class="form-group">
                <%= f.label :feed_rate, class: 'control-label' %>
                <%= f.number_field :feed_rate, step: :any, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :service_rate, class: 'control-label' %>
                <%= f.number_field :service_rate, step: :any, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :atmosphere_rate, class: 'control-label' %>
                <%= f.number_field :atmosphere_rate, step: :any, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :review_comment, class: 'control-label' %>
                <%= f.text_field :review_comment, class: 'form-control' %>
              </div>
              
              <%= f.submit %>
          <% end %>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <%= link_to 'Control work final', root_path, class: 'navbar-brand' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
          <li><%= link_to 'New Place', new_establishment_path %></li>
          <li><%= link_to "Hello, #{current_user.name}!", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul><!-- /.login toolbar -->
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControlWorkFinal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% if notice || alert %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>

</html>